[path]
cache = "~/.cache/pepdocs/pep_{pep_number:04d}.txt"


[url]
pep_repo = "https://raw.githubusercontent.com/python/peps/master"
pep_web  = "https://peps.python.org/pep-{pep_number:04d}/"

    [url.pep]
    txt = "{pep_repo}/pep-{pep_number:04d}.txt"
    rst = "{pep_repo}/pep-{pep_number:04d}.rst"
